baseURL = 'http://example.org/'
languageCode = 'en'
title = '420-SN1-A24'
theme = "relearn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
  themeVariant = "zen-dark"

# Hide the Home entry.
# Default: false
# If shown, a Home button will appear below the search bar and the main menu.
# It links to your the home page of the current language.
disableLandingPageButton = true
